### ISSUE TITLE
[BUG] Amethyst Censoring Profiles?

### ISSUE THREAD

**Issue by DeMoN100** [vitorpamplona/amethyst#575] opened 2023-09-06 13:14 UTC
**Describe the bug**
Everytime I see a profile with nudity in it amethyst automatically blocks & hides the profile. I even unblock them but they get automatically blocked again & do not appear in the spammers & blockers list.

**To Reproduce**
Steps to reproduce the behavior: Look at a profile that has notes with nudity

**Expected behavior**
Nothing should happen

**Video and Screenshots**
If applicable, add a video and/or screenshots to help explain your problem.

**Device (please complete the following information):**
- Pixel 5a
- Android 13
- App Version v0.75.14
I would have made this a discussion but there is no board here so I submitted it as a bug report because this is a problem as well. I shouldn't have profiles being blocked automatically & hidden just because they load some nudity in a note. This should only be hidden with a filter switch & not blocked from my profile so I may never see nudity again & put somewhere that you can't even find them on the block & spam list the profiles are not there.

**Comment by greenart7c3** [comment] 2023-09-06 13:54
Try changing the content warning options in the note options menu

![image](https://github.com/vitorpamplona/amethyst/assets/115044884/4895d2c7-f315-438b-89ab-391b27fa08e3)

**Comment by davotoula** [comment] 2023-09-06 15:48
Have you tried unticking the below? I believe amethyst uses reports from other users to block spam. 

![Screenshot_20230906-174659.png](https://github.com/vitorpamplona/amethyst/assets/1747287/46222c52-cc7d-4aea-adb5-2b2a01788c1f)

**Comment by DeMoN100** [comment] 2023-09-09 06:22
> Have you tried unticking the below? I believe amethyst uses reports from other users to block spam.
> 
> ![Screenshot_20230906-174659.png](https://user-images.githubusercontent.com/1747287/266066235-46222c52-cc7d-4aea-adb5-2b2a01788c1f.png)

These are already unchecked & this is happening. They do not appear in the block or spammer list.

> Try changing the content warning options in the note options menu
> 
> ![image](https://user-images.githubusercontent.com/115044884/266029680-4895d2c7-f315-438b-89ab-391b27fa08e3.png)
This isn't about content warnings some profiles get blocked automatically & when I unblock them it automatically blocks them in 3 seconds afterwards. If I leave their profile page they get hidden.

**Comment by vitorpamplona** [comment] 2023-09-09 11:02
Do you have a specific profile for us to look at. I just checked some profiles with sensitive content and they show correctly when filters are disabled.

**Comment by vitorpamplona** [comment] 2024-02-03 00:00
I couldn't reproduce this one. Closing for now.

**Closed by vitorpamplona** 2024-02-03 00:00 UTC
